### Send POST request with json body
POST http://localhost:8081/employees
Content-Type: application/json

{
  "name": "Ting, Ki",
  "age": 26,
  "language": "Solidity",
  "balance": 1000.0,
  "gender": "Male"

}

### GET request with parameter
GET http://localhost:8081/employees/3

### GET request with parameter
GET http://localhost:8081/employees/firstName/Ting

### GET request with parameter
GET http://localhost:8081/employees?lastName=Ki&page=1&size=3&column=id&direction=DESC

###
PUT http://localhost:8081/employees
Content-Type: application/json

{
  "id": 3,
  "name": "Keith, Kuo",
  "age": 42,
  "language": "Java"
}

###
PATCH http://localhost:8081/employees
Content-Type: application/json

{
  "age": 200,
  "id": 3
}

###
DELETE http://localhost:8081/employees/2